demo/vue-viewer/src/components/ElementInspector.vue
demo/vue-viewer/src/components/ElementSelector.vue
demo/vue-viewer/src/components/PageInspector.vue
demo/vue-viewer/src/components/WordHierarchy.vue
demo/vue-viewer/src/vuex/store.js

The expansion panels in Document Viewer now mantain their state (expanded / closed) when switching between tabs

[Vue] added persistence to expansion panels state in Document Viewer

---

.drone.yml
.gitignore
docker-compose-build.yml
docker-compose.yml
docker/tags.sh
docs/docker.md

Now, a simple docker-compose up starts everything (even a demo UI).
For development, the docker-compose-build.yml can be used
Updated the doc as well

Correct some problems with the docker-compose

---

api/server/src/ServerManager.ts
api/server/src/api.ts

Citing #82:
> **Description**
> Currently, the default server configuration is supplied along with the project source.
> In a deployed environment, the client cannot be automatically notified if the server's defaults are changed.
> An API endpoint /default-config could provide this information, which would remove the need to hardcode anything on the client/GUI side.
> 
> EDIT: changed the proposition from /defaultConfig to /default-config to follow api endpoint naming convention.

Resolves #82 : Adding default configuration retrieval possible using the API

---

package.json

The single quotes in the npm script made them non-compatible under windows.
Just fixed that with escaped double-quotes.

Make `npm run format` windows compatible

---

server/assets/TableDetectionScript.py
server/src/processing/TableDetectionModule/TableDetectionModule.ts

In some cases table lines are not properly detected and we need to configure camelot in order to be more precise in table lines detection [(Camelot short lines parameter)](https://camelot-py.readthedocs.io/en/master/user/advanced.html#detect-short-lines).
Before (last row missing 1 cell)
After (last row with 2 cells)
Also added tolerance when finding words in cell box because some times words box are not perfect fitted into cell box

Improved Table detection

---

server/src/input/pdfminer/pdfminer.ts

There are some cases "testReadingOrder.pdf" that pdfminer extracts empty words with no attributes that makes parsr to create worng words
- See <text> <text> in pdfminer extraction.
- See wrong behaviour -> Three words 'A' 'X' 'A'
- See fixed behaviour -> One word 'AXA'

[PdfMiner] Skip using empty words

---

server/bin/index.ts
server/src/utils.ts

When image based pdf is uploaded we are using imagemagick convert tool to generate an image from each page in order to be used as tesseract input.
We were using wrong command 'convert' (that works on MacOs but not in Windows) instead of use 'magick convert' (see https://imagemagick.org/script/convert.php)

Fixed wrong ImageMagick command 'convert' used in Windows environment

---

server/src/processing/Module.ts

Fixed issue that solves false boolean in custom options. 
Currently if default module options has a boolean with true value we are not able to set that value to false

Module Options

---

package.json
server/src/input/extract-fonts.ts
server/src/input/pdf2json/pdf2json.ts
server/src/input/pdfminer/pdfminer.ts
server/src/processing/TableDetectionModule/TableDetectionModule.ts
server/src/utils.ts

Two issues are covered here:
1. Running `mocha **/*.spec.ts` will run tests everywhere, including
those in `node_modules`. The fix scopes it to `test/**/*.spec.ts`.
2. Shell invocations of `where` or `which` assume an english response.
The fix takes into account the return code instead (fortunately, both
commands happen to return the same status codes.)

Fix test execution

---

server/src/input/pdfminer/pdfminer.ts
server/src/output/markdown/MarkdownExporter.ts
server/src/processing/LinesToParagraphModule/LinesToParagraphModule.ts
server/src/processing/ListDetectionModule/ListDetectionModule.ts
server/src/types/DocumentRepresentation/List.ts

Refactor of:
- PdfMiner: Remove '-A' (means graphics extraction) from pdf2txt command because there are files crashing if -A is used (for instance Benchmark --> axa.uk.business.owntools.pdf)
- Headings: Extract all fonts from all words not only using most used in each line.
Before
After
- Lists detection: Improved regex to find bullet or numeric lists.
Before
After
- List: allow list detection from any line in a paragraph not only from first line.
Before
After
Test Paragraph benchmark:
- From: 21/10/2019 - 9% - 70/746
- To: 28/10/2019 - 42% - 378/881

MD exporter / Headings / Lists refactor

---

server/bin/index.ts
server/src/input/pdfminer/pdfminer.ts
server/src/input/set-page-dimensions.ts
server/src/input/tesseract/tesseract2json.ts
server/src/processing/OutOfPageRemovalModule/OutOfPageRemovalModule.ts
server/src/types/TsvElement.ts
server/src/utils.ts

- Bounding boxes and other fields were not being casted as number based objects but strings instead, which caused the `OutOfPageModule` to remove almost all elements from the tesseract output.
- This PR fixes that issue.

[Tesseract] Fixes a type casting issue in Tesseract extraction

---

api/swagger/openapi.yaml
api/swagger/swagger-generated.yaml
docs/api.html

We have a security requirement to change these email addresses.
I checked with them and we can have the official AXA open source email address instead.

Change email address in Swagger for opensource@axa.com

---

demo/vue-viewer/public/index.html
demo/vue-viewer/src/router.js

Simple and small improvements on the Parsr Web Demo.

Redirect demo to /upload instead of empty Home. Change title to Parsr from vue-viewer.

---

docker/parsr-base/Dockerfile

Following https://github.com/axa-group/Parsr/pull/168
Cleanup Docker image from pdf2json

removing pdf2json from Docker image

---

package.json
server/src/types/DocumentRepresentation/Heading.ts

Fixed md generation in Headings as max level supported by MD is 6
After
Before

Heading max markdown level 

---

server/src/types/DocumentRepresentation/Word.ts

Add backslashes on dot and closing parentheses after numbers to comply to Markdown standards.

Escape Markdown Numbers when not a List

---

api/server/src/ProcessManager.ts
server/src/input/pdfminer/pdfminer.ts

Some PDFs cannot be read by pdfminer because of DRMs. I added qpdf to remove them before feeding the PDF to pdfminer.

add qpdf in the repairpdf pipeline

---

server/src/input/pdfminer/pdfminer.ts
server/src/types/PdfminerFigure.ts

Currently the figure elements only contained images, but apparently the
figure elements can also contain text.
This makes required changes for this flexibility to be available.

[pdfminer] Patch - Let figures contain text elements too

---

server/src/Orchestrator.ts
server/src/input/extract-fonts.ts
server/src/input/pdfminer/pdfminer.ts
server/src/input/tesseract/tesseract2json.ts
server/src/processing/TableDetectionModule/TableDetectionModule.ts

1. Proper chain qpdf -> mutool -> extraction
2. Store the correct repaired filename in the Document object
3. Make sure the `TableDetectionModule` executes on the repaired file

[Issue #188] Correctly execute qpdf; store the repaired file's name on Doc

---

server/src/processing/LinesToParagraphModule/LinesToParagraphModule.ts
test/paragraph-merge.spec.ts
test/unit/lines-to-paragraph.spec.ts

Improve headings detection to fix some bugs.
Each line with same font in purple box has to be a heading (we expect to have 1 purple box for each line with same font)
- Before
- After
Test files: 
[Headings_Consecutives.pdf](https://github.com/axa-group/Parsr/files/3809218/Headings_Consecutives.pdf)
[Headings_Consecutives_single_lines.pdf](https://github.com/axa-group/Parsr/files/3809219/Headings_Consecutives_single_lines.pdf)

Heading Fixes

---

server/assets/TableDetectionScript.py
server/defaultConfig.json
server/src/processing/TableDetectionModule/README.md
server/src/processing/TableDetectionModule/TableDetectionModule.ts
server/src/processing/TableDetectionModule/defaultConfig.json

This will allows the user to execute multiple camelot runs on the document, using different customized options to increase accuracy on table detection.
It's the first step on solving this clubhouse story:
https://app.clubhouse.io/parsr/story/3031/tables-aren-t-detected-in-this-pdf
**TODO**: find a better name for the `pageConfig` option 🤔

[TableDetection] - modified TableDetectionModule configuration options

---

server/src/input/pdfminer/pdfminer.ts
server/src/utils.ts

[This recent pdfminer.six commit](https://github.com/pdfminer/pdfminer.six/commit/bc034c8e59d90e9b2cb8697a1d2fe9a33401761e#diff-147654f85909c4dee04d20e37ebb576f) requires pdf2txt.py to be executed like this:
> `python pdf2txt.py <args>`
Making necessary changes to be up to speed with the latest version.

[pdfminer] Call pdfminer with the python interpreter

---

demo/vue-viewer/src/components/ElementSelector.vue
demo/vue-viewer/src/components/FontInspector.vue
demo/vue-viewer/src/vuex/store.js

Javascript error is thrown in UI when a document contains images.
To reproduce:
- Run parsr with benchmark/dataset/Samples_of_descriptive_paragraphs.pdf
- Go to page 2
- See console

Avoid UI to crash when image is detected in a document

---

demo/vue-viewer/src/components/ElementInspector.vue

In the UI, when an element's content was an Array of other elements, we were not able to inspect the contents inside that Array.
This PR does a deep-search for 'content' values inside Arrays or Objects and returns it as a string.
This is specially useful for inspecting a Cell or Row inside tables, but it's applied for every type of element available.

[Vue] - added recursive getter for element contents

---

server/bin/index.ts

Resolves #212
When we start OCRing all the images inside a pdf, the part `- p.getElementsOfType(Image).length` from the following should be removed:
https://github.com/axa-group/Parsr/blob/274bcc10e74cb00b8af7a6a1f2b18a11edf86783/server/bin/index.ts#L130-L131

[#212] Consider only textual elements before OCR relaunch at zero texts

---

server/src/types/DocumentRepresentation/Heading.ts

removed condition that limited the heading level to max 6 when converting to Markdown

[HeadingToMD] - unlimited MD heading level

---

docs/installation.md

add pdfminer.six in the dependencies when installing on a debian based distribution

update the documentation for installation

---

server/src/input/pdfminer/pdfminer.ts

Apparently pdfminer uses a [0,1] range for cmyk as well as rgb.

use range [0,1] instead of [0,100] for cmyk colors

---

demo/vue-viewer/src/components/DocumentPreview/Page.vue
demo/vue-viewer/src/components/Thumbnails.vue
package.json
server/assets/ImageCorrection.py
server/bin/index.ts
server/src/input/tesseract/TesseractExtractor.ts
server/src/input/tesseract/tesseract2json.ts
server/src/output/json/JsonExporter.ts
server/src/types/DocumentRepresentation/JsonExport.ts
server/src/types/DocumentRepresentation/Page.ts
server/src/utils.ts

This PR tries to optimise images before run tesseract.
1) Detect and fix rotation to use 0 degrees rotated images in tesseract
2) Detect text face direction to ensure text is face up before run tesseract
3) Removes shadow images to improve Tesseract accuracy

Image optimisation before tesseract scan

---

server/assets/ImageCorrection.py
server/bin/index.ts
server/src/processing/OutOfPageRemovalModule/OutOfPageRemovalModule.ts
server/src/types/DocumentRepresentation/Page.ts
tslint.json

Fixed bug that was removing words from a page with rotated content.
When we rotate a page to get best tesseract accuracy we need to use rotated box instead of page box to filter elements that are out out of page.
After
Before

Out of page removal & image rotation

---

server/bin/index.ts
server/src/input/tesseract/TesseractExtractor.ts
server/src/utils.ts

Allow tesseract to OCR pdfs with more than one page, also optimised Pdf to Image (magick convert) to generate better resolution and lower weight images to use in tesseract.
Test pdf --> 
[fbiletter.pdf](https://github.com/axa-group/Parsr/files/3945556/fbiletter.pdf)

Tesseract & multi pages PDF's

---

.gitignore
server/src/input/tesseract/TesseractExtractor.ts

- Skip creating directory to save tesseract optimised images if it already exist
- Updated git ignore to add folder --> /test/assets/samples

Fix test execution crash

---

server/src/input/tesseract/TesseractExtractor.ts

Convert images from PDF using RGB color space because tesseract fails using as input images with CMYK color space.
Use benchamrk -> FLYER1.pdf
Before: Pipe fails running tesseract extractor
After: Pipe works

Tesseract CMYK to RGB

---

docker/parsr-base/Dockerfile
package-lock.json
package.json
server/src/input/email/EmailExtractor.ts
test/unit/input-extractors.spec.ts

to correctly run Puppeteer (html2pdf tool used by EmailExtractor)
Edited: Drone fails because it does not rebuild the base image on a PR commit, and that is needed for this case to get the new required puppeteer dependencies. This should be safe to merge to develop.

[fix] - extra dependencies added to Dockerfile

---

demo/vue-viewer/src/components/DocumentPreview/Page.vue
demo/vue-viewer/src/components/PageInspector.vue
demo/vue-viewer/src/vuex/store.js
server/src/input/pdf.js/pdfjs.ts
server/src/output/json/JsonExporter.ts
server/src/types/DocumentRepresentation/JsonExport.ts

Added page margins visualization in the VUE GUI :
This will ease the debugging of margins-related bugs like the one in this story:
https://app.clubhouse.io/parsr/story/3482/header-footer-detection

[feature/page-margins] - added page margin visualization for the GUI

---

server/bin/index.ts

Leaves out the .pdf mention from the outputted results' filenames.
Example: Converts 'results.pdf.md' to 'results.md' for the initial file 'results.pdf'.

Omits input filename extension in the outputted filenames

---

server/src/processing/PageNumberDetectionModule/PageNumberDetectionModule.ts

same conditions than HeaderFooterDetection module, to avoid setting 'isHeader', 'isFooter' and 'isPageNumber' if margins were not calculated

[fix] - added conditions for the PageNumberDetection execution

---

server/src/input/email/EmailExtractor.ts

renamed temporal PDF file used by EmailExtractor. This files are deleted after being generated by the tests

Fix / .eml tmp files

---

README.md

Just a small typo fix of the URL to Pdfminer.six license

Fix broken link to Pdfminer.six license

---

api/server/src/ProcessManager.ts
api/server/src/api.ts
demo/vue-viewer/src/components/UploadConfig/ConfigItem.vue
demo/vue-viewer/src/services/DocumentServices.js
demo/vue-viewer/src/views/Upload.vue
demo/vue-viewer/src/vuex/store.js
server/bin/index.ts
server/src/input/OcrExtractor.ts
server/src/input/google-vision/GoogleVisionExtractor.ts
server/src/input/tesseract/TesseractExtractor.ts
server/src/input/tesseract/tesseract2json.ts
server/src/output/json/JsonExporter.ts
server/src/types/DocumentRepresentation/Page.ts
server/src/utils.ts
test/number-digits-preservation.spec.ts

- added tesseract, abbyy and google-vision options for image extraction in the UI
- if google-vision is selected, an aditional file is required: the Google credentials JSON file.
This credentials can be generated for free in Google Cloud Platform, and an enabled billing account is required.
- if google-vision is executed via CLI, it's required to set an environment variable before calling the tool: `GOOGLE_APPLICATION_CREDENTIALS=/absolute/path/to/file.json`
https://app.clubhouse.io/parsr/story/4492/new-ocr-google
- also, a minor cosmetic bug is fixed in this PR: https://app.clubhouse.io/parsr/story/4526/cosmetic-issue-with-the-arrow-on-the-ui
**TODO**: add more input formats for Google Vision (only images supported for now)

[google-vision] - added image extraction options to the UI

---

demo/vue-viewer/src/components/DocumentPreview/Word.vue

When running an OCR with no font information provided then ensure UI displays words using 'estimated' font size base on bounding box height.

Ocr & font size in UI

---

server/src/utils/CommandExecuter.ts

Ensure only expected images are used to be ran by ocr. 
Benchmark files are all in same folder then previously we were returning all images included in that folder instead of only 'converted ones'

Pdf to image

---

server/src/processing/ImageDetectionModule/ImageDetectionModule.ts

fixed bug on ImageDetectionModule where an image object is missing its xObjId property

[fix] - filter images with no xObjId property

---

docker/parsr-base/Dockerfile
docs/installation.md

changed `pip install camelot-py` to `pip install camelot-py[cv]` as it is the recommended way to install camelot and it adds a required package for Parsr to work fine with table detection: opencv-python

[fix/camelot] - edited camelot installation command

---

server/src/utils/CommandExecuter.ts

fixed typo on `magick` command

[hotfix] - typo on magick command

---

server/src/utils/CommandExecuter.ts

`mutool extract` sometimes extracted images with .pam extension, breaking the copy into assets folder and the rendering on GUI.
this new param tells mutool to extract every image as PNG.

fix mutool and .pam image files

---

demo/vue-viewer/package-lock.json
docker/parsr-base/Dockerfile
docs/installation.md
package-lock.json
package.json
preinstall-scripts/darwin.bash.sh
preinstall-scripts/windows.commands.js
server/src/input/email/EmailExtractor.ts
server/src/utils.ts

- Removed direct usage of GhostScript command to merge PDF files (used in EmailExtractor).
- Replaced that gs command with [pdfmerge](https://www.npmjs.com/package/pdfmerge) package.
- Added **PyPDF2** to the installation guides and scripts, as it's a required dependency of pdfmerge.
- **Extra:** ran `npm audit fix` on vue-viewer folder.

Removed direct usage of GhostScript

---

server/bin/index.ts

Removed old behaviour to OCR image-based pdf because Image Module Detection is the owner of this feature.
Bug reference #347

Legacy ocr behaviour

---

server/defaultConfig.json
server/src/processing/HeadingDetectionModule/HeadingDetectionModule.ts
server/src/processing/TableOfContentsDetectionModule/TableOfContentsDetectionModule.ts

- Moved TableOfContentsDetectionModule to be executed before HeadingDetectionModule.
- Removed Heading references inside TOCDetection.
- On HeadingDetectionModule, filtered elements inside TOC to **not** be interpreted as Headings.

[toc] - fixed issue with table of contents

---

sonar-project.properties

Add exclusion for pdf.worker.js because is a node module configuration file

SonarQube - Remove pdf.worker.js from analysis

---

server/src/input/pdfminer/PdfminerExtractor.ts
server/src/input/pdfminer/pdfminer.ts
server/src/types/DocumentRepresentation/Word.ts
server/src/types/Metadata/Properties.ts
server/src/types/PdfminerTextbox.ts

Fixed a bug with pdf2txt `--detect-vertical` argument were some characters are interpreted as vertical text, splitting the word in two. (vertical detection is working as usual)
**Before:**
```
Headings
- Identical heading detected: 305 / 1099 (27.75)%
- Detected heading (wrong lvl): 675 / 1099 (61.41)%
- False Positive : 583
- Missed Heading : 424
```
**After:**
```
Headings
- Identical heading detected: 387 / 1099 (35.21)%
- Detected heading (wrong lvl): 793 / 1099 (72.15)%
- False Positive : 465
- Missed Heading : 306
```

Fixed split words bug on pdf2txt result

---

docs/installation.md

- Arch linux no longer contains pdfminer[.six] as an official package. We have to pass through PIP.
- Camelot-py requires =< py3.7 (for now)

Updating Installation Instructions

---

server/src/utils/CommandExecuter.ts

- added new parameter to pdf2txt.py to avoid word splitting on file icann.pdf
related issue: https://github.com/pdfminer/pdfminer.six/issues/402

[split-words] - added param to pdf2txt to avoid word splitting

---

scripts/copyFiles/index.js
server/bin/index.ts

The idea ios that we use the default config file for CLI if no config file is provided -> Ease of use.
- Change the index.ts to support a default vaule to defaultConfig.json
- Change copy asset script to bundle the defaultConfig in the dist folder.

Add a default config file for CLI

---

package-lock.json
package.json

Fixes for vulnerabilities (usage of minimist < 1.2.5) found in:
- html to pdf
- TsLint
Using [npm-force-resolutions](https://www.npmjs.com/package/npm-force-resolutions) we are able to force version used by sub dependencies.

[Vulnerabilities Fix] Force version of sub dependencies

---

server/bin/index.ts
server/defaultConfig.json
server/src/output/index.ts
server/src/output/simpleJson/README.md
server/src/output/simpleJson/SimpleJsonExporter.ts
server/src/types/Config.ts
server/src/types/DocumentRepresentation/Heading.ts
server/src/types/DocumentRepresentation/List.ts
server/src/types/DocumentRepresentation/Paragraph.ts
server/src/types/DocumentRepresentation/Table.ts
server/src/types/DocumentRepresentation/TableOfContents.ts

Use the simpleJSON:true in config to activate the simple Json output.
This json output will be save as filename.simple.json in the out dir.
It's structured is simplified and easier to use for building quick usecases.

Add a simple JSON output that is easier to use.

---

scripts/copyFiles/index.js
scripts/preinstall/darwin.commands.js
scripts/preinstall/index.js
scripts/preinstall/windows.commands.js
test/table-detection.spec.ts

- used [license-header-checker](https://github.com/lsm-dev/license-header-checker/ ) to detect and "fix" files without the license header.
- disabled tslint rule on a couple of lines (pre-commit hook was failing)

[license] - added missing license headers

---

server/src/processing/TableOfContentsDetectionModule/TableOfContentsDetectionModule.ts

Exclude words detected as Footer or Header from being part of a TOC
- Before
- After

Table of contents

---

server/src/types/DocumentRepresentation/Page.ts

Exclude images from page margins module because they usually overlaps page margins and can also be "full screen" size.
After

Page Margins 

---

demo/vue-viewer/src/components/DocumentPreview/Page.vue
server/assets/ImageCorrection.py
server/src/processing/ImageDetectionModule/ImageDetectionModule.ts

- Update 'ImageCorrection.py' to last openCV version (parameters renamed)
- Update 'ImageCorrection.py' to output int instead of strings (align behaviour between page rotation and contents rotation inside Page.vue)
- Store 'page rotation' object in document (regression bug added when we remove pdf to images conversion when no text was detected in order to OCR all pages)

Rotated Images

---

server/src/processing/DrawingDetectionModule/DrawingDetectionModule.ts
server/src/types/DocumentRepresentation/BoundingBox.ts
server/src/types/DocumentRepresentation/Drawing.ts
server/src/utils.ts

- on `groupShapesIntoDrawing` function, adapted the target box to the current SvgLines array instead of always using the page box, reducing the iteration count on the while block. Also the while condition was using `height` and `width` instead of `bottom` and `right`, finishing the iteration before reaching the actual end of the box.
- on `Drawing` class, replaced Math.max and Math.min with a custom function to calculate those values. Math.max and Math.min throw `max call stack size exceeded` for very big arrays. Explanation [here](https://stackoverflow.com/questions/42623071/maximum-call-stack-size-exceeded-with-math-min-and-math-max).

DrawingDetectionModule fixes

---

.drone.yml
docker/parsr-base/Dockerfile
docker/parsr-base/policy.xml

New policy in ImageMagick desactivate PDF parsing by default.
This PR to change that behaviour using the `policy.xml` file

fix for the new behaviour in ImageMagick in baseimage

---

server/src/processing/HeaderFooterDetectionModule/HeaderFooterDetectionModule.ts
server/src/processing/HeaderFooterDetectionModule/README.md
server/src/processing/HeaderFooterDetectionModule/defaultConfig.json

- Fix ignore pages when it is set in config file.
- Treatment is now done on group of pages by similar size. This similarity size is a new option set to 10% by default.
- Treatment is done only on group of pages with more than one page.
Header and footer are set correctly within the percentage value, however the dash line on UI are still based on the margins value of the last group of page, as for now margins are a doc property and not a page property.  
Some files to test the behavior:
[multipleFormats_001.pdf](https://github.com/axa-group/Parsr/files/4895580/multipleFormats_001.pdf)
[multipleFormats_002.pdf](https://github.com/axa-group/Parsr/files/4895582/multipleFormats_002.pdf)
[multipleFormats_003.pdf](https://github.com/axa-group/Parsr/files/4895584/multipleFormats_003.pdf)
Correct …

Header footer fix

---

server/assets/HeadingLevelPrediction.py
server/src/processing/MlHeadingDetectionModule/MlHeadingDetectionModule.ts
server/src/utils/CommandExecuter.ts

**Before:** the model was loaded again and again for the predictions of the headings' levels
**Now:** it is loaded only once

Model loading

---

clients/python-client/pyproject.toml

Bumping python client's version to 3.2.3 to accomodate recent Readme changes before publishing to PyPi.

python client version bump to 3.2.3

---

server/src/processing/ImageDetectionModule/ImageDetectionModule.ts
server/src/processing/ImageDetectionModule/README.md
server/src/processing/ImageDetectionModule/defaultConfig.json
server/src/processing/ImageDetectionModule/extractors/PdfminerImageExtractor.ts
server/src/types/Metadata/Properties.ts

- With pdfMiner, the source of the image is now inside of the json export (already worked with pdfjs).
Json output exemple:
```
{
"metadata": [],
"pages": [
{
"margins": { "top": 46, "left": 57 },
"box": { "l": 0, "t": 0, "w": 720, "h": 540 },
"rotation": { "degrees": 0, "origin": { "x": 0, "y": 0 }, "translation": { "x": 0, "y": 0 } },
"pageNumber": 1,
"elements": [
{
"id": 975,
"type": "image",
"properties": { "order": 0, "cr": 711.02, "cl": 10.52 },
"metadata": [],
"box": { "l": 17.32, "t": 2.21, "w": 27.52, "h": 55.73 },
"src": "/var/folders/0x/05yl4x4j1nj6qsd_p9tbbh5m0000gn/T/e38cdaa736de437855f29dae9e7430/img-0032.png",
"refId": "Im4",
"xObjId": "32",
"xObjExt": "png"
},
```
- Add an option to enable to set the source of the image inside the properties of extracted data from ocr. …

[json_image_src] Add the source of image in img.src

---

clients/python-client/parsr_client/parsr_client.py

> The context of this PR is laid out in full in #498 
This PR allows the python client parsr_client.ParsrClient to support a specified `request_id`, on occasions when `save_request_id` is false. Currently, if a specific ID is provided in output methods like `get_json()` and `get_markdown()`, an `UnboundLocalError` is raised.
I think this is due to an indentation error that means the get request from the server is only issued if no `request_id` is provided.
The error does not occur with get_status() which is an identical GET implementation but for the indentation of this request line.
It would seem sensible to add unit tests here, but there aren't currently other tests in place for the python client. I can try and work on some general tests in this space, but that'd significantly extend …

[fix parsr_client #498] Fix indentation in client GET requests

---

.github/workflows/codeql-analysis.yml
package-lock.json
package.json

Fix backend security issues.
Node 10+ is now required for Google Vision API.

Security patch of Google Vision to 2.1.2.

---

demo/vue-viewer/package-lock.json
demo/vue-viewer/package.json
demo/vue-viewer/src/views/ViewerMarkdown.vue

Change frontend markdown renderer to `marked` from `vue-markdown` because the latter had major security issues and is no longer maintained.

Replace legacy vue-markdown with marked

---

docker/parsr-base/Dockerfile

- Pinned scikit-learn to match the version (0.23.2) of the pickled model training data provided with the server. Up until now, the build scripts downloaded the latest version (0.24.2 as of today) which causes the server to crash on heading detection (see https://scikit-learn.org/stable/modules/model_persistence.html) -> **Another possibility might be to resolve this dependency in the parsr image (as opposed to parsr-base) if frequent updates are intended, but I didn't introduce that change**
- Fixed installation of opencv-python taking unnecessarily long (it was supposedly being compiled on install; see https://github.com/3b1b/manim/issues/1213)
- Tested building images from scratch, run without errors

Pinned scikit-learn version; fixed opencv-python installation taking longer than neccessary

---

.gitignore
server/src/output/simpleJson/SimpleJsonExporter.ts
server/src/types/DocumentRepresentation/Element.ts
server/src/types/DocumentRepresentation/Heading.ts
server/src/types/DocumentRepresentation/List.ts
server/src/types/DocumentRepresentation/Paragraph.ts
server/src/types/DocumentRepresentation/Table.ts
server/src/types/DocumentRepresentation/TableOfContents.ts

This adds page number to simple json outputs in headings, paragraphs, tables, etc. This allows an application handling text to show the original pdf page, possibly with annotations.

Add page number to simple json output

---

docs/configuration.md

Updated to the new version of words-to-line module. The old example produces the same error as in #493:
```
/opt/app-root/src/dist/src/Cleaner.js:201
throw new Error("Module " + moduleClass.moduleName + " has unresolved dependencies (" + unresolvedStr + ").");
^
Error: Module lines-to-paragraph has unresolved dependencies (words-to-line-new).
at Cleaner.checkDependenciesAndAdd (/opt/app-root/src/dist/src/Cleaner.js:201:19)
at /opt/app-root/src/dist/src/Cleaner.js:136:19
at Array.forEach (<anonymous>)
at Cleaner.parseLatestConfig (/opt/app-root/src/dist/src/Cleaner.js:123:16)
at new Cleaner (/opt/app-root/src/dist/src/Cleaner.js:88:18)
at main (/opt/app-root/src/dist/bin/index.js:72:19)
at Object.<anonymous> (/opt/app-root/src/dist/bin/index.js:204:1)
at Module._compile …
```

[documentation] update example config

---

clients/python-client/parsr_client/parsr_client.py

If  `silent==False`, the code inside the while would never re-evaluate the `server_status_response`, leading to a infinite loop. 
`'>> Job done!'` should be printed after the last while iteration.

possible infinte loop fix if silent is False
