axa-group/Parsr

docs/modules/reading-order-detection-module.md, server/src/modules/ReadingOrderDetectionModule.ts
Add column width as an option for reading order, allow to force a minimum width which is usefull for some ref number / option list.
=> Add minimum column width as an option to reading order

README.md
=> PDFMiner and Camelot deployment instructions inclusion

server/src/extractors/pdfminer/pdfminer.ts
=> Patched pdfminer to check for pages with no text before populating

server/src/input/extract-fonts.ts, server/src/input/pdf2json/pdf2json.ts, server/src/processing/TableDetectionModule/TableDetectionModule.ts, server/src/utils.ts
Check for the location of the python interpreter before calling it.
=> Resolves #63

demo/vue-viewer/src/components/NavBar.vue, demo/vue-viewer/src/router.js, demo/vue-viewer/src/services/DocumentServices.js, demo/vue-viewer/src/views/ViewerMarkdown.vue, demo/vue-viewer/src/views/ViewerText.vue, demo/vue-viewer/src/vuex/store.js
A minimal Text and Mardown viewer in new UI.
It is usefull for debug, but should be improved upon in the future.
=> Initial version raw text / markdown viewer

.drone.yml, docker/tags.sh
No docker build on PR event in CI
Fix docker typo
=> Fix tag name on develop

docker/parsr-base/Dockerfile, docker/parsr/Dockerfile, docker/parsr/build.sh
Also fix an issue that prevent parsr code to be updated in the docker image.
=> Fix permission problem in Openshift if no PVC are used.

demo/vue-viewer/src/components/DocumentPreview/Word.vue, demo/vue-viewer/src/components/ElementInspector.vue, demo/vue-viewer/src/services/DocumentServices.js, demo/vue-viewer/src/vuex/store.js
Added a hardcoded white-space at the end of word text if next word box has 0 spacing
=> [Vue] Word Space

server/src/processing/LinesToParagraphModule/LinesToParagraphModule.ts
=> [Issue-115] PdfMiner using document with Tables crash pipeline execution 

server/src/processing/WordsToLineModule/WordsToLineModule.ts
=> PdfMiner forces wrong behaviour in WordsToLine Module

demo/vue-viewer/src/components/DocumentPreview/Word.vue, demo/vue-viewer/src/vuex/store.js, server/defaultConfig.json, server/src/input/pdfminer/pdfminer.ts, server/src/processing/LinkDetectionModule/LinkDetectionModule.ts, server/src/types/DocumentRepresentation/Paragraph.ts, server/src/types/DocumentRepresentation/Word.ts
Some changes in MD exporter and other stuff to achieve better benchmark accuracy
=> PdfMiner & Markdown exporter refactor

docs/api-guide.md
Added the following to the API Readme:
> ## 4. Server Configuration Access
> 
> The API can also be queried to gain access to the following server assts:
> 
> 1. **Default Configuration**: The server's default configuration can be queried (at `/api/v1/default-config`) using:
> 
> 		curl -X GET \
> 		http://localhost:3001/api/v1/default-config
> 
> 2. **List of Modules**: The list of all usable modules can be queried from the server (at `/api/v1/modules`) using:
> 
> 		curl -X GET \
> 		http://localhost:3001/api/v1/modules
> 
> 3. **Module Configuration**: A module's configuration file, which includes name, description and each module parameter's default value and range can be queried (at `/api/v1/module-config/<module_name>`) using:
> 
> 		curl -X GET \
> …
=> [API] [Doc] Documenting the new configuration and module access endpoints on the API

package-lock.json, package.json, server/assets/TableDetectionScript.py, server/src/output/markdown/MarkdownExporter.ts, server/src/types/DocumentRepresentation/Element.ts, server/src/types/DocumentRepresentation/Heading.ts, server/src/types/DocumentRepresentation/Line.ts, server/src/types/DocumentRepresentation/Paragraph.ts, server/src/types/DocumentRepresentation/Table.ts, server/src/types/DocumentRepresentation/TableCell.ts, server/src/types/DocumentRepresentation/TableRow.ts
Some changes to achieve better accuracy (use Nlv.1_Page_1.pdf fromBenchmark repo)
=> Improve Table to MD

package.json
=> increased mocha timeout to 10 seconds

server/src/output/markdown/MarkdownExporter.ts, server/src/types/DocumentRepresentation/Heading.ts, server/src/types/DocumentRepresentation/Paragraph.ts
Added changes to achieve better testParagraph accuracy.
- Allow export Paragraph/Heading as html inside tables or as MD outside tables
- Refactor Heading to MD
- Improved Line break for lines in a paragraph
TestParagraph accuracy from 9% to 14%
=> Heading & Pragraph Improvments

server/src/input/pdfminer/pdfminer.ts
1) remove space between chars in a word
2) avoid removing all spaces between line words
In case we detect a line with both cases then we will remove all <text> </text>
=> PdfMiner Fixed issues

demo/vue-viewer/src/components/ElementInspector.vue, demo/vue-viewer/src/components/ElementSelector.vue, demo/vue-viewer/src/components/NextPrevButtons.vue, demo/vue-viewer/src/mixins/selectAndHighlight.js, demo/vue-viewer/src/vuex/store.js, server/src/input/pdf2json/pdf2json.ts, server/src/processing/LinesToParagraphModule/LinesToParagraphModule.ts, server/src/processing/LinesToParagraphModule/defaultConfig.json, server/src/processing/LinkDetectionModule/LinkDetectionModule.ts, server/src/types/DocumentRepresentation/Heading.ts
- Define maxLineDistance to avoid lines separated by huge distance become joined into a paragraph.
- Export headings html using 'b' instead of 'strong'
Before
After
=> Lines to paragraph

package.json, server/src/input/extract-fonts.ts, server/src/input/pdf2json/pdf2json.ts, server/src/input/pdfminer/pdfminer.ts, server/src/processing/LinesToParagraphModule/LinesToParagraphModule.ts, server/src/processing/LinesToParagraphModule/defaultConfig.json, server/src/processing/TableDetectionModule/TableDetectionModule.ts, server/src/types/DocumentRepresentation/Heading.ts, server/src/utils.ts
Reverts axa-group/Parsr#158
This PR was merged into master by accident. It will be moved to develop branch
=> Revert "Lines to paragraph"

demo/vue-viewer/src/components/DocumentPreview/List.vue, demo/vue-viewer/src/components/DocumentPreview/Page.vue, demo/vue-viewer/src/components/PageInspector.vue, demo/vue-viewer/src/views/Viewer.vue
Added component for lists and add switch filter
=> Allow List to be displayed in UI

api/server/package.json
From `"Sacha Bron"` to `"AXA rev"`.
=> Remove personal information from API package.json

demo/vue-viewer/src/router.js
Sorry for the previous warning. :)
=> Remove unused dependency from Vue router.js

server/src/output/text/TextExporter.ts, server/src/types/DocumentRepresentation/List.ts
Allow lists to generate raw text.
Fixes #9 
Please close #9 when merged
=> Raw Text Exporter

README.md, README_zh-cn.md, api/server/package-lock.json, api/server/package.json, api/server/src/api.ts, package-lock.json, package.json
Instead of use pdf-image that is not working on Windows we're now using 'pdf2pic' that is expected to work on Windows
=> Removed pdf-image as there is a Critical vulnerability

docker/parsr-base/Dockerfile
add graphicsmagick package in the parsr-base image
=> add graphicsmagick

demo/vue-viewer/src/components/DocumentPreview/Word.vue
Fix #186 
Please close bug when PR is approved
=> [Issue-186] Skip white font color

server/src/input/extractImagesFonts.ts, server/src/input/pdfminer/PdfminerExtractor.ts
Renamed the file extracting fonts + images to reflect its function
=> [Refactor] mutool extract part in the pipeline renamed

server/src/processing/LinkDetectionModule/LinkDetectionModule.ts
catching an error in the dumppdf.py output
=> [patch/link-creation-foolproofing-for-README.pdf]

server/src/output/markdown/MarkdownExporter.ts
added 'new page' separators in markdown exporter
=> [Markdown] - page separators for MD exporter

server/bin/index.ts, server/src/input/extractImagesFonts.ts, server/src/input/pdfminer/pdfminer.ts, server/src/input/set-page-dimensions.ts, server/src/input/tesseract/tesseract2json.ts, server/src/output/pdf/PdfExporter.ts, server/src/processing/LinkDetectionModule/LinkDetectionModule.ts, server/src/processing/TableDetectionModule/TableDetectionModule.ts, server/src/utils.ts
1. Makes Parsr compatibile with both Imagemagick versions 6 and 7.
2. Introduces new in-house spawn and syncSpawn functions that accept multi-word commands.
=> [Imagemagick] Resolves #239 - ImageMagick backward compatibility, Flexible spawn functions

server/src/input/pdfminer/pdfminer.ts
modify "ncolourToHex" to handle output from pdfminer in the form of (r,
g,b) as well as [r,g,b]. Also handle the similar case with cymk
=> improve color detection

server/src/input/set-page-dimensions.ts, server/src/utils.ts
Added same solution to support 'identify' in both image Magick 6 & 7 versions
=> Allow Identify (ImageMagick) to work on V6 & v7

server/src/input/pdfminer/pdfminer.ts
=> [Bugfix] [Pdfminer] Undefined colors are handled

server/src/utils.ts
Added logs into running image rotation feature because there is an error in docker execution
=> [Docker & Image Rotation] Added logs to trace error details

server/assets/ImageCorrection.py, server/src/utils.ts
As current docker installation has openCV 3.2.0 we need to add compatibility to opencv 3.X & 4.X
=> Feature image rotation & docker

demo/vue-viewer/package-lock.json, demo/vue-viewer/package.json, tslint.json
Fix this
https://github.com/axa-group/Parsr/network/alert/demo/vue-viewer/package-lock.json/serialize-javascript/open
=> Serialize javascript vulnerability Fixed

server/src/processing/HeadingDetectionDTModule/model.js, server/src/processing/LinkDetectionModule/LinkDetectionModule.ts, server/src/types/DocumentRepresentation/Page.ts
A few files:
1. `server/src/processing/LinkDetectionModule/LinkDetectionModule.ts `
2. `server/src/types/DocumentRepresentation/Page.ts`
3. `server/src/processing/HeadingDetectionDTModule/model.js`
...contained some code which prohibited the pre-commit hook from proceeding.
This PR fixes them.
=> [Patch] [Lint] Linter issues in a few files

README.md, docker/parsr-base/Dockerfile, docker/parsr/build.sh
Includes `pipenv` in the docker base image.
=> [Docker] [BaseImage] Pipenv inclusion

README.md, docker/parsr-base/Dockerfile, docker/parsr/build.sh
This reverts commit 57143a9bdadcf60e3561524fc821a67b4dba92b0.
=> Revert "[Docker] [BaseImage] Pipenv inclusion (#271)"

server/src/output/json/JsonExporter.ts, server/src/processing/ImageDetectionModule/ImageDetectionModule.ts, server/src/types/DocumentRepresentation/Image.ts
Just turn Off image detection module in UI and "Parsr" one pdf with images, the UI and main Json should not contain any image data
=> Skip Images if Image Detection Module is Off

server/src/types/DocumentRepresentation/Paragraph.ts
fixes clubhouse https://app.clubhouse.io/parsr/story/4741/error-with-document
=> fixes error 'Reduce of empty array with no initial value'

server/src/output/json/JsonExporter.ts
Fixes https://github.com/axa-group/Parsr/issues/305
=> [Issue 305] Fixed missing heading level in output json

api/server/src/ProcessManager.ts, api/server/src/api.ts, demo/vue-viewer/src/services/DocumentServices.js, demo/vue-viewer/src/views/Upload.vue, server/src/input/abbyy/AbbyyTools.ts
Allow UI to configure required Abby parameters instead of have them hardcoded
=> Abbyy + UI

demo/jupyter-notebook/parsr-jupyter-notebook.ipynb
=> Removing a garbage cell from jupyter

server/src/input/pdfminer/PdfminerExtractor.ts, server/src/input/pdfminer/pdfminer.ts
=> [Issue-299 Fix] Avoid null pointer reference

docs/api-guide.md
updated api-guide doc with info for new download parameter
=> [docs] - updated api-guide.md

package.json, server/assets/ImageCorrection.py, server/bin/index.ts, server/src/input/OcrExtractor.ts, server/src/input/doc/DocxExtractor.ts, server/src/input/email/EmailExtractor.ts, server/src/input/extractImagesFonts.ts, server/src/input/pdf.js/pdfjs.ts, server/src/input/pdfminer/PdfminerExtractor.ts, server/src/input/pdfminer/pdfminer.ts, server/src/input/set-page-dimensions.ts, server/src/input/tesseract/tesseract2json.ts, server/src/output/csv/CsvExporter.ts, server/src/output/pdf/PdfExporter.ts, server/src/processing/ImageDetectionModule/ImageDetectionModule.ts, server/src/processing/LinkDetectionModule/LinkDetectionModule.ts, server/src/processing/TableDetectionModule/TableDetectionModule.ts, server/src/utils.ts, server/src/utils/CommandExecuter.ts
- Ensure last pdfminer version works properly (last version requires to be ran like 'python pdf2txt.py args'
- Encapsulate all third party dependencies calls are in one file
- Attempts to fix https://github.com/axa-group/Parsr/issues/311
=> PdfMiner 20200124

server/src/input/pdfminer/pdfminer.ts
Fixed bug parsing attached file
[5207-deep-neural-networks-for-object-detection.pdf](https://github.com/axa-group/Parsr/files/4214360/5207-deep-neural-networks-for-object-detection.pdf)
=> PdfMiner xml parser issue

server/src/input/pdfminer/PdfminerExtractor.ts, server/src/types/DocumentRepresentation/Page.ts
fixed problem that caused pipeline to crash when processing dataset document `20-ArticleText-Paragraph_0.18.pdf`
=> [hotfix] - fixed error with document

package-lock.json, package.json
'cp' was not working on windows. replaced it with 'copyfiles' npm package that is already being used.
=> [fix/cp] - removed 'cp' command in package.json

demo/vue-viewer/src/components/DocumentPreview/Page.vue
Ensure UI doesn't overlaps pages & only rotate UI pages when angle is 90,180 or 270
=> Page rotation fix

server/bin/index.ts, server/defaultConfig.json, server/src/Cleaner.ts, server/src/Orchestrator.ts, server/src/input/abbyy/AbbyyTools.ts, server/src/processing/ImageDetectionModule/DumpPdfParsr.ts, server/src/processing/ImageDetectionModule/ImageDetectionModule.ts, server/src/processing/ImageDetectionModule/README.md, server/src/processing/ImageDetectionModule/defaultConfig.json, server/src/processing/Module.ts, server/src/utils.ts
Given images detected by Image detection module now we are able to configure the module (new module parameter) also for data extraction using selected OCR in config file.
Fixes #179 #23 
Sample of document with `OCR image = false` and same document `OCR image = true`
=> Image Detection Module - OCR detected Images to extract data

README.md
Updated readme with minor changes due new features
=> Parsr readme

demo/vue-viewer/src/views/Upload.vue
=> [UI] - fixed text overflow on progress modal

demo/vue-viewer/package-lock.json, demo/vue-viewer/package.json
Attempts to fix [vulnerabilities](https://github.com/axa-group/Parsr/network/alerts)
=> Vulnerabilities fixes

api/server/package-lock.json, demo/vue-viewer/package-lock.json, package-lock.json
Fixed api/server -> multer vulnerability [fix](https://github.com/expressjs/multer/issues/858)
=> Vulnerabilities fix - Part II

package-lock.json, package.json
Updated to `mocha@v7.1.1`
Still pending 2 issues:
=> Vulnerability Fix - Part III 

.drone.yml, sonar-project.properties
=> sonarqube in CI

server/src/input/pdfminer/PdfminerExtractor.ts, server/src/input/pdfminer/pdfminer.ts
Removes not supported chars by xml 1.0 specification.
See reported files in [Club House](https://app.clubhouse.io/parsr/story/6248/xml-read-error)
Technical issue logs:
=> Pdfminer - Xml sanitise

server/src/utils/CacheLayer.ts, server/src/utils/CommandExecuter.ts
- added simple in-memory cache for dumppdf command
(executed once on ImageDetectionModule if doc has images, and later on LinkDetectionModule)
=> dumppdf cache

server/src/input/pdfminer/pdfminer.ts
Fixes #372 
Using pdfminer a figure can contain texts in nested figures and prev implementation was only using texts in root figure
=> Fix for issue 372

docs/installation.md
Recent repo changes + command line format requirement needs these changes to make the installation instructions to work on Arch Linux.
=> Arch installation procedure update

api/server/src/api.ts, docs/api-guide.md
Add a default config file path if not provided in api.ts
=> [API defaultConfig.json] Add a default config file if not provided

api/server/src/api.ts, docs/configuration.md, server/bin/index.ts, server/src/Cleaner.ts, server/src/processing/Module.ts, server/src/types/Config.ts
-Add check for required keys + Default value in the documentation
-Add check inside of key modules and print info about misspelling or not set key and it's default value.
=> Check config file

clients/python-client/README.md, clients/python-client/README.rst, clients/python-client/parsr_client/parsr_client.py, clients/python-client/pyproject.toml
Minor function bump to fetch document name from a request ID
=> Python client v3.1

server/src/processing/RegexMatcherModule/RegexMatcherModule.ts
-When the regex is not global, we use the match() method.
-Add in the while condition to use re.exec(0 if regex is global(if not infinite loop).
=> [Fix Regex Global] If regex is not global use of match().

demo/vue-viewer/src/components/DocumentPreview/Page.vue, demo/vue-viewer/src/views/Upload.vue, server/bin/index.ts, server/src/input/Extractor.ts, server/src/input/OcrExtractor.ts, server/src/input/abbyy/AbbyyClient.ts, server/src/input/abbyy/AbbyyTools.ts, server/src/input/abbyy/AbbyyToolsXml.ts, server/src/input/amazon-textract/AmazonTextractExtractor.ts, server/src/input/google-vision/GoogleVisionExtractor.ts, server/src/input/ms-cognitive-services/MicrosoftCognitiveServices.ts, server/src/input/tesseract/TesseractExtractor.ts
This PR allows:
- Select Abby as extractor
- Use xml Abbyy generated file as input
Sample XML:
[Foo_Abbyy.zip](https://github.com/axa-group/Parsr/files/4539060/Foo_Abbyy.zip)
Pending to test more files using Abby, will be done when I receive an Abbyy server license.
=> Abbyy extractor & abbyy xml files as input

server/src/processing/HeadingDetectionModule/HeadingDetectionModule.ts, server/src/processing/MlHeadingDetectionModule/MlHeadingDetectionModule.ts, server/src/processing/TableDetection2Module/TableDetection2Module.ts, server/src/processing/TableDetectionModule/TableDetectionModule.ts
First step to increase table accuracy:
- text contents inside tables are not treated as Headings.
- filtered some false 1x1 tables with no content.
- on TableDetection2, added check for false tables.
=> Table accuracy - Part 1

demo/vue-viewer/src/components/DocumentPreview/Page.vue, demo/vue-viewer/src/components/DocumentPreview/TableRow.vue, demo/vue-viewer/src/components/DocumentPreview/Word.vue, demo/vue-viewer/src/components/DocumentPreview/Zoom.vue, demo/vue-viewer/src/components/ElementInspector.vue, demo/vue-viewer/src/components/WordHierarchy.vue
-Delete some commented code
-Change name of variables defined outer scope
-Parameter with default value placed at the end of parameters
-Add some alt attributs
=> [clean viewer component] modify variable names, add alt attributs

demo/vue-viewer/src/components/ElementSelector.vue, demo/vue-viewer/src/vuex/store.js
-Store a function in variable
-Use of async / await instead of "then" in for loop to avoid some technical debt
=> [minor refactor] Minor refactor reduce technical debt

demo/doc-versioning/doc_versioning/gui/css/normalize.css, demo/doc-versioning/doc_versioning/gui/document.html, demo/doc-versioning/doc_versioning/src/backend/server.py
-Remove duplicated font and add alternatives
-Remove some commented code
-Add caption and <th scope="col"> to table to make it compliant with web accessibility
-Rename a variable with python naming convention
=> Clean doc versioning

demo/vue-viewer/src/views/Upload.vue
=> [Issue 431]

clients/python-client/parsr_client/parsr_client.py, clients/python-client/pyproject.toml
=> Enabling initialising python client to load with an existing revision history

server/src/utils/DumpPdfUtils.ts
Fixed bug that caused pipeline to crash when processing attached document.
[ETAT DATE BEL 01042020.pdf](https://github.com/axa-group/Parsr/files/4656129/ETAT.DATE.BEL.01042020.pdf)
=> fix pipeline crash

clients/python-client/README.md, clients/python-client/parsr_client/parsr_client.py, clients/python-client/parsr_client/parsr_output_interpreter.py, clients/python-client/pyproject.toml
1. Python client doc
2. version bump
3. readme iteration
=> Python client doc + version bump + readme iteration

demo/vue-viewer/src/components/PageInspector.vue, server/bin/index.ts, server/defaultConfig.json, server/src/output/json/JsonExporter.ts, server/src/processing/TableDetection2Module/README.md, server/src/processing/TableDetectionModule/TableDetectionModule.ts, server/src/types/Config.ts
More improvements for TableDetectionModule:
- Improvements for "isFalseTable" and "drawingIsTable" functions based on benchmark docs. This reduces false positives and increases detection accuracy.
- Fix: use pageNumber instead of page array index to work with drawingsDoc on TableDetectionModule.
- Added optional parameter `includeDrawings` on config output options. When this is set to `true`, doc on Document's `drawingsFile` property will be merged with the main document, and final json output will contain Drawings and SvgLines info. Defaults to `false` for simplicity and retrocompatibility. This new param is very useful for debugging and visualizing Drawings on UI.
- Restored Drawings switch on UI (only shown when `includeDrawings: true` on config file).
Accuracy before:
```json …
```
=> Table accuracy improvements

CONTRIBUTING.md, README.md, README_pt.md, README_sp.md, docs/configuration.md, docs/installation.md, docs/simple-json-output.md, server/src/output/README.md, server/src/output/csv/README.md, server/src/output/json/README.md, server/src/output/markdown/README.md, server/src/output/pdf/README.md, server/src/output/simpleJson/README.md, server/src/output/text/README.md
Updated:
- configuration.md (config.json file explanation)
- CONTRIBUTING.md (develop is no more the default branch)
- main README's had table of contents with bad format
- output modules: better explanation and examples for each module. Also added missing explanation for SimpleJson format.
- installation guide: fixed wrong Camelot installation link
=> Documentation - Part 1

server/src/types/DocumentRepresentation/Table.ts
csv exporter was not working correctly when the table had cells with spans > 1
example table:
Before: (note the extra semicolons at each row)
After:
=> [csv-export] - fix export with spanned cells

server/src/processing/KeyValueDetectionModule/README.md, server/src/processing/KeyValueDetectionModule/defaultConfig.json, server/src/processing/RegexMatcherModule/README.md
- Added explanation on README for KeyValueDetection and RegexMatcher modules
- fixed bad structure on KeyValueDetection default config values
=> Documentation

server/src/processing/MlHeadingDetectionModule/MlHeadingDetectionModule.ts
HeadingDetectionModule was not awaiting for the level calculation process to finish
=> FIX / Headings Level

docs/installation.md
=> Add sklearn to pip install under Linux

scripts/preinstall/darwin.bash.sh
Also in response to #463 , sklearn and tabula were missing inside preinstall script.
=> [sklearn tabula preinstall] add sklearn and tabula to preinstall script

clients/python-client/parsr_client/parsr_client.py
Fix bug #488 
Correct names of value => no error showing up
=> [fix parsr_client #488] Rename values when wait_till_finished=true

demo/doc-versioning/doc_versioning/gui/document.html, demo/doc-versioning/doc_versioning/gui/index.html, demo/echo-module-py/echo-module.py
Add some security fix:
-Define the content-type in echo-module.py
-Avoid unsafe target blank with the balise rel="noopener noreferrer" in demo/doc-versioning/doc_versioning/gui/index.html
-Add click jacking protection in demo/doc-versioning/doc_versioning/gui/document.html
=> Security fix

clients/python-client/parsr_client/parsr_client.py
The method 'send_document' had olld docstrings. 
file --> file_path
config --> config_path
add server
=> Update docstring for send_document method
